#!/bin/bash

INFILE=$1
OUTFILE=$2

BASE_URL=https://lindat.mff.cuni.cz/services/udpipe/api/process

MODEL=nb  # Norwegian (bokmål)

PARAMS="-F data=@$INFILE -F tokenizer= -F tagger= -F parser= -F model=$MODEL"

curl $PARAMS "$BASE_URL" | jq -r ".result" > $OUTFILE
